LoanApply/LoanApply/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls')),
]

LoanApply/accounts/urls.py
from django.urls import path, include
from accounts import views

app_name = "accounts"

urlpatterns = [
    path('', views.signup, name="signup"),
    path('signin/',views.loginview, name="login"),
    path('logout/',views.loggedout, name="logout"),
    path('change_pwd/', views.change_pwd, name="change_pwd"),
]

LoanApply/home/urls.py
from django.urls import path, include
from home import views

app_name = "home"

urlpatterns = [
    path('', views.home_page, name="homely"),
    path('profile/', views.profile_page, name="profile_page"),
    path('financial/', views.financial_page, name="financial"),
    path('combined/', views.cibilbank_form, name='cibilbank_form'),
    path('eligibility/', views.eligibility_check, name='eligibility_check'),
    path('personal/', views.personal, name="personal"),
]

LoanApply/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <title>
        {% block title %}
            
        {% endblock %}
    </title>
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-pzjw8f+ua7Kw1TIq0i7z5PEbiRH4f5tKrdu0k5l8r9UkwrI0PpZFcD94WMEF6EBI" crossorigin="anonymous"></script>
    <!-- In the <head> tag for Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Before the closing </body> tag for Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.min.css" integrity="sha384-NvKbDTEnL+A8F/AA5Tc5kmMLSJHUO868P+lDtTpJIeQdGYaUIuLr4lVGOEA1OcMy" crossorigin="anonymous">

    {% block css_block %}
    
    {% endblock %}

  </head>
  <body class="bg-light">

    {% include 'navbar.html' %}

    <div class="container" style="padding-top:20px">
      <div class="messages container mt-2">
        {% if messages %}
          {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{message.tags}} {% endif %} alert-dismissible" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert"> <!-- aria-level="Close" -->
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
      </div>
    </div>

    <div class="container" style="padding-top:20px">
    {% block body_block %}

    {% endblock %}
    </div>

    {% block js_block %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

LoanApply/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom">
    <div class="container">
        <!-- Left-aligned Brand -->
        <a class="navbar-brand" href="{% url 'home:homely' %}">Digital Loan Management System</a>

        <!-- Hamburger button for smaller screens -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar Items -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <button class="btn btn-primary dropdown-toggle" id="navbarDropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                            </svg>
                            {{ request.user }}
                        </button>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item text-primary" href="{% url 'home:homely' %}">Home</a>
                            <a class="dropdown-item text-primary" href="{% url 'accounts:change_pwd' %}">Change Pwd</a>
                            <a class="dropdown-item text-primary" href="{% url 'home:personal' %}">Profile</a>
                            <hr class="dropdown-divider">
                            <a class="dropdown-item text-primary" href="{% url 'accounts:logout' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <!-- Login/Signup -->
                    <li class="nav-item">
                        <a href="{% url 'accounts:login' %}" class="btn btn-info btn-md">Login</a>
                        <a href="{% url 'accounts:signup' %}" class="btn btn-info btn-md">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Include Bootstrap JS and Popper.js for proper functionality of navbar and other elements -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>